name = "sociale_fintech/social-finance-contracts"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'sociale_fintech/social-finance-contracts'"

[repository]
user = "sociale_fintech"
project = "social-finance-contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
